---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: git
spec:
  serviceName: git
  selector:
    matchLabels:
      app: git
  replicas: 1
  template:
    metadata:
      labels:
        app: git
    spec:
      containers:
      - name: git
        image: "quay.io/mmuraki/git_http_server:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: "REPOSITORIES"
          value: "parasol-insurance"
        volumeMounts:
        - name: data
          mountPath: /data
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: git
spec:
  selector:
    app: git
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: git
spec:
  port:
    targetPort: 3000
  tls:
    termination: edge
  to:
    kind: Service
    name: git
    weight: 100
  wildcardPolicy: None
