apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: Llama-3-ELYZA-JP-8B
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  labels:
    opendatahub.io/dashboard: "true"
  name: llama-3-elyza-jp-8b
  namespace: user1
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: pytorch
      name: ""
      resources:
        limits:
          nvidia.com/gpu: "1"
        requests:
          nvidia.com/gpu: "1"
      runtime: llama-3-elyza-jp-8b-vllm
      storage:
        key: aws-connection-shared-minio
        path: models/Llama-3-ELYZA-JP-8B
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
