---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: setup-objectstorage-work
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-objectstorage
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: setup-objectstorage
        image: quay.io/mmuraki/model_uploader:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args:
        - -c
        - |-
          aws s3 rm --recursive s3://${NAMESPACE} 2>/dev/null
          aws s3 rm --recursive s3://${NAMESPACE}-pipelines 2>/dev/null
          set -e
          aws s3 ls --recursive s3://${NAMESPACE} 2>/dev/null
          cd /mnt
          rm -rf ./*
          git clone https://huggingface.co/elyza/Llama-3-ELYZA-JP-8B
          rm -rf Llama-3-ELYZA-JP-8B/.git
          aws s3 cp --recursive Llama-3-ELYZA-JP-8B s3://${NAMESPACE}/models/Llama-3-ELYZA-JP-8B
          curl -o accident_detect.onnx https://rhods-public.s3.amazonaws.com/demo-models/ic-models/accident/accident_detect.onnx
          aws s3 cp accident_detect.onnx s3://${NAMESPACE}/models/accident_detect/1/accident_detect.onnx
          git clone https://huggingface.co/Systran/faster-whisper-large-v3
          rm -rf faster-whisper-large-v3/.git
          aws s3 cp --recursive faster-whisper-large-v3 s3://${NAMESPACE}/models/faster-whisper-large-v3
          set +e
          aws s3 mb s3://${NAMESPACE}-pipelines
          aws s3 ls --recursive s3://${NAMESPACE}
          aws s3 ls --recursive s3://${NAMESPACE}-pipelines
        envFrom:
        - secretRef:
            name: aws-connection-shared-minio
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AWS_ENDPOINT_URL
          value: http://minio.ic-shared-minio.svc.cluster.local:9000
        volumeMounts:
        - name: work
          mountPath: /mnt
      volumes:
        - name: work
          persistentVolumeClaim:
            claimName: setup-objectstorage-work
      restartPolicy: Never
