---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: processing-pipeline-storage
  labels:
    opendatahub.io/dashboard: "true"
  name: processing-pipeline-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
