---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ic-shared-app

commonLabels:
  component: ic-claim-chatbot

resources:
- deployment-app.yaml
- service-app.yaml
- route-app.yaml
- maven.yaml
