= プロンプトエンジニアリング演習（オプション）
include::_attributes.adoc[]

NOTE: この {ic} の部分はオプションとしてマークされています。したがって、ラボの他の部分に影響をあたえずにスキップすることができます。 {ic-lab}全体を完了したあと、もし時間が余ったらいつでも戻ってくることができます。

IMPORTANT: ChatGPTやその他の商用サービスとやりとりする際には、望ましくない結果や仕事に適さない結果が得られるのを防ぐために、多くのガードレールが設置されています。私たちの{ic} したがって、安全な方法で作業を行い、得られた結果が自分自身および/または対象ユーザーにとって適切であることを確認するのは、あなた自身の責任となります。この {ic} の作成者は、あなたが得た結果が

これまでのセクションで見てきたように、モデルから得られる結果に影響を与えるさまざまな要因があります：モデルのパラメータ、プロンプト、クエリ、そしてもちろんデータそのもの...。

それでは、これらの異なる要素をどのように調整すれば最良の結果が得られるかを見ていきましょう。

== 設定の変更

ノートブック `03-01-nb-llm-example.ipynb` に戻って変更してみてください：

- `temperature` のような llm パラメータを変更して、モデルをよりクリエイティブにします
- `prompt template` を変更して、モデルの挙動を変化させます。例えば、答えを詩の形式で返すようにします。あるいは、企業環境でより役立つように、異なるタイプの聴衆に答えるようにします。例えば、5歳の子供、あるいは技術的知識のない人、またはその反対の人などです。
- `query` 自体は、プロンプトの特定の側面を上書きするために使用できます。これは、ユーザーのクエリを事前フィルタリングするなど、「プロンプト注入」に対するガードレールを設置することが重要である理由を示しています。

== データの変更

ノートブック `03-02-summarization.ipynb` に戻り、以下を変更してみましょう。

- 理解しにくいように、新しいクレームを編集または作成します。（注：Jupyterでjsonファイルを編集するには、右クリックして「Open With > Editor」を選択します）
- 異なる言語で実験してみましょう

== プロンプトの変更

ノートブック `03-03-information-extraction.ipynb` に戻り、以下を変更してみてください。

- 理解しにくい新しい請求を編集または作成する
- 日付と時刻の抽出において、モデルをより正確かつ簡潔にするよう試みる。例えば、特定のフォーマットに従うように
